### ISSUE TITLE
Add Python 3.11 as a supported version (and to Actions)

### ISSUE THREAD

**Issue by Loreith** [s-zeng/dhall-python#147]
**Summary:**

It looks like something previously blocked supporting 3.11, but when I downloaded and compiled this package today against 3.11 it built without any errors.

The build was on x86 MacOS, cpython 3.11.3, rustc 1.69.0 in case there are any troubles reproducing.

I... don't have an in-depth understanding of how pypi works, but I'm assuming that including 3.11 support means doing something with GitHub actions to build the wheel and publish it, and that that isn't something I can submit a PR for. If it is, apologies, and please point me in the direction of doing the work!

**Comment by s-zeng** [comment]
Closed with release 0.1.15
