### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by s-zeng** [s-zeng/dhall-python#21]
Between CI builds #99 and #100 (both of which are routinely scheduled weekly builds with no code changes in between), the build ceased to complete successfully. I did some light maintenance PRs to see if I could resolve them, but it appears that I will have to take more time to investigate.

I am currently a bit strapped for free time to look at this; in the meantime, I can confirm that building from source works properly, and that the previously built artifacts and PyPI binaries still work as expected. So this isn't something terribly urgent, for the meantime, at least until serde_dhall/dhall-lang gets more updates.

When that happens, or if any users have any urgent needs, this will be addressed more urgently. Until then, thank you for the patience

**Comment by nickray** [comment]
@s-zeng I think you just have to merge https://github.com/s-zeng/dhall-python/pull/22.
As you can see, the associated CI run goes through. Bumping serde-dhall to 0.10 in the AUR PKGBUILD also works fine. It's not clear to me why though, the CHANGELOG in serde-dhall gives no indication of changes that seem relevant.

**Comment by s-zeng** [comment]
Hey Nick, thanks for pointing that out. I've merged the pr

**Comment by nickray** [comment]
Here's the cause: https://github.com/Nadrieril/dhall-rust/issues/210

**Comment by nickray** [comment]
See also https://github.com/s-zeng/dhall-python/pull/26 which should fix everything.

**Comment by s-zeng** [comment]
Builds are passing now, so closing issue!
