### ISSUE TITLE
home-anchored imports don't work

### ISSUE THREAD

**Issue by padhia** [s-zeng/dhall-python#41]
Not sure if this is an upstream *dhall-rust* issue, but according to the [dhall documentation](https://docs.dhall-lang.org/tutorials/Language-Tour.html#file-imports), the dhall language supports *home-anchored* imports as shown in the following example. The Python version however seems to support only the relative and absolute imports, but not the home-anchored import. 

```
❯ dhall <<< '~/test.dhall'
"hello"

❯ python
>>> import dhall
>>> dhall.loads('./test.dhall')
'hello'
>>> dhall.loads('~/test.dhall')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Error(Dhall(Error { kind: Typecheck(TypeError { message: Custom("error: error\n --> <current file>:1:1\n  |\n1 | ~/test.dhall\n  | ^^^^^^^^^^^^ No such file or directory (os error 2)\n  |") }) }))
```

**Comment by s-zeng** [comment]
This appears to be an upstream issue, I have reported it here: https://github.com/Nadrieril/dhall-rust/issues/223

I will close this issue if/when the upstream issue is closed.

**Comment by padhia** [comment]
Thank you!

**Comment by s-zeng** [comment]
Looks like upstream fixed the issue [here](https://github.com/Nadrieril/dhall-rust/commit/826b2fdd633eb207b893ddc2a4ded71f44d3ecf9), now just waiting for a new version to update dhall-python with

**Comment by s-zeng** [comment]
Fixed in https://github.com/s-zeng/dhall-python/releases/tag/v0.1.12
