### ISSUE TITLE
Add Cargo.lock to repo

### ISSUE THREAD

**Issue by hejfelix** [s-zeng/dhall-python#48]
I'm trying to create a nix-build definition for this project, which in turn would let us build the ARM version for the new macbooks, but the recommended way is to use an existing lock-file. Since there is none in this repo, I had to manually create one. 
According to the nix docs, it's also best practice for rust projects to keep this in version control. I'm sure there's a reason it's ignored here, but if not, I would love for it to be included in the repo :)

**Comment by s-zeng** [comment]
Good plan. Currently busy but will get around to when I have time. Send up a pull request if you like and I'll approve it

**Comment by hejfelix** [comment]
https://github.com/s-zeng/dhall-python/pull/49

**Comment by s-zeng** [comment]
Closed by #49
