### ISSUE TITLE
Dhall scripts using value sharing are not properly deserialized

### ISSUE THREAD

**Issue by KOLANICH** [s-zeng/dhall-python#65]
```python
res = dhall.loads("""
let o1 = {c = 2}
let res = {a = o1, b = o1}
in res
""")
assert res["a"] is res["b"] // AssertionError
```

**Comment by s-zeng** [comment]
This is expected behaviour. Dhall will normalize the input first, so the python never sees that the same constant is used twice in the final dictionary.

So this code is exactly equivalent to

```
dhall.loads("""{a = {c = 2}, b = {c = 2}}""")
```

Let me know if you have any more questions
