### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by s-zeng** [s-zeng/dhall-python#7]
It would be nice to be able to install this from the AUR. Perhaps we can have issues as well for packaging else where, but the AUR seems like the easiest place to start for me personally.

**Comment by nickray** [comment]
https://aur.archlinux.org/packages/python-dhall/ ?

**Comment by s-zeng** [comment]
What do you know, someone got to it first! Thanks @KokaKiwi

**Comment by KokaKiwi** [comment]
I didn't even know this issue existed :laughing:

> @nickray
> It does not build though, with the same error as in s-zeng/dhall-python/actions/runs/524240146.
> Bumping serde-dhall to 0.10 fixes.

I published a bump on the AUR package `pkgrel` with the patch updating the `serde-dhall` dependency to fix the issue.

**Comment by s-zeng** [comment]
> I didn't even know this issue existed laughing
> 
> > @nickray
> > It does not build though, with the same error as in s-zeng/dhall-python/actions/runs/524240146.
> > Bumping serde-dhall to 0.10 fixes.
> 
> I published a bump on the AUR package's `pkgrel` with the patch updating the `serde-dhall` dependency to fix the issue.
> 
> Edit: Wait i now just have to update to the `0.1.7` version...

Thanks for the quick update!
